propose:
  description: >
    You are proposing the motion: {motion}.
    Come up with a clear argument in favor of the motion.
    Be very convincing.
  expected_output: >
    A list with 5 bullet points of the most relevant information about {motion}
  agent: proposer
  output_file: output/propose.md

oppose:
  description: >
    You are opposing the motion: {motion}.
    Come up with a clear argument against the motion.
    Be very convincing.
  expected_output: >
    A list with 5 bullet points of the most relevant information about {motion}
  agent: opposer
  output_file: output/oppose.md

decide:
  description: >
    Review the arguments presented by the debaters and decide which side is more convincing.
  expected_output: >
    Your decision on which side is more convincing, and why.
  agent: judge
  output_file: output/decide.md